process.env.NODE_ENV = 'test'; process.env.DATABASE_PATH = './data/test.db'; process.env.JWT_SECRET = 'test-secret-that-is-long-enough-to-be-safe';
const fs = require('fs'); const path = require('path'); const dbPath = path.resolve(__dirname, '../data/test.db'); try { fs.rmSync(dbPath); } catch {}
const test = require('node:test'); const assert = require('node:assert/strict'); const request = require('supertest'); const app = require('../src/app');
let token; let resourceId;
test('health endpoint succeeds', async () => { const res = await request(app).get('/health'); assert.equal(res.status, 200); assert.equal(res.body.data.status, 'ok'); });
test('registration validates and creates an account', async () => { const invalid = await request(app).post('/api/v1/auth/register').send({ name: 'A', email: 'bad', password: 'short' }); assert.equal(invalid.status, 400); const res = await request(app).post('/api/v1/auth/register').send({ name: 'Test User', email: 'test@example.com', password: 'a secure password' }); assert.equal(res.status, 201); token = res.body.data.token; assert.ok(token); });
test('authentication rejects unauthenticated access and accepts login', async () => { const forbidden = await request(app).get('/api/v1/dashboard/state'); assert.equal(forbidden.status, 401); const login = await request(app).post('/api/v1/auth/login').send({ email: 'test@example.com', password: 'a secure password' }); assert.equal(login.status, 200); });
test('resource CRUD enforces ownership and validation', async () => { const auth = { Authorization: `Bearer ${token}` }; const bad = await request(app).post('/api/v1/resources/tasks').set(auth).send({ data: [] }); assert.equal(bad.status, 400); const made = await request(app).post('/api/v1/resources/tasks').set(auth).send({ data: { title: 'Study safely', done: false } }); assert.equal(made.status, 201); resourceId = made.body.data.id; const list = await request(app).get('/api/v1/resources/tasks?search=Study&page=1&limit=10').set(auth); assert.equal(list.status, 200); assert.equal(list.body.meta.total, 1); const updated = await request(app).put(`/api/v1/resources/tasks/${resourceId}`).set(auth).send({ data: { title: 'Study safely', done: true } }); assert.equal(updated.status, 200); const deleted = await request(app).delete(`/api/v1/resources/tasks/${resourceId}`).set(auth); assert.equal(deleted.status, 204); const missing = await request(app).get(`/api/v1/resources/tasks/${resourceId}`).set(auth); assert.equal(missing.status, 404); });
test('state sync saves and reloads dashboard state', async () => { const auth = { Authorization: `Bearer ${token}` }; const saved = await request(app).put('/api/v1/dashboard/state').set(auth).send({ state: { theme: 'cosmic', tasks: [{ title: 'A' }] } }); assert.equal(saved.status, 200); assert.equal(saved.body.data.state.theme, 'cosmic'); const loaded = await request(app).get('/api/v1/dashboard/state').set(auth); assert.equal(loaded.body.data.state.tasks[0].title, 'A'); });
test('malformed JSON receives a safe client error', async () => { const res = await request(app).post('/api/v1/auth/login').set('Content-Type', 'application/json').send('{broken'); assert.equal(res.status, 400); assert.equal(res.body.success, false); });
test('upload rejects an unauthenticated request', async () => { const res = await request(app).post('/api/v1/documents/upload').attach('file', Buffer.from('hello'), 'note.txt'); assert.equal(res.status, 401); });
test('the error handler does not expose unexpected server errors', () => { const { errorHandler } = require('../src/middleware/error'); let body; const res = { status(code) { assert.equal(code, 500); return this; }, json(value) { body = value; } }; errorHandler(new Error('sensitive internal detail'), { id: 'test-request' }, res); assert.equal(body.error.message, 'Internal server error'); assert.equal(body.error.requestId, 'test-request'); });

test('authenticated upload is private and retrievable by its owner', async () => { const auth = { Authorization: `Bearer ${token}` }; const uploaded = await request(app).post('/api/v1/documents/upload').set(auth).attach('file', Buffer.from('hello'), { filename: 'note.txt', contentType: 'text/plain' }); assert.equal(uploaded.status, 201); const file = await request(app).get(uploaded.body.data.url).set(auth); assert.equal(file.status, 200); assert.match(file.headers['content-disposition'], /note.txt/); });
